In [1]:
import os
import pandas as pd
from tqdm.notebook import tqdm
from datetime import datetime

# 读取标签

In [2]:
label = pd.read_feather("/home/datamake117/test0121/label_divide1_5.fea")
label['index'] = pd.to_datetime(label['index'])
label = label.set_index('index', drop=True)
label  # 1494 rows × 5314 columns (index: 2019-01-02 - 2025-03-04)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688583,301602,688545,001356,001395,688411,302132,301173,301557,603409
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-07,0.002208,-0.016575,-0.025453,NaN,-0.027386,-0.000573,-0.001470,-0.012743,-0.008051,-0.003991,...,-0.026894,0.000192,-0.000232,0.009245,0.001958,0.025914,0.011188,NaN,NaN,NaN
2025-03-10,-0.009476,-0.019777,-0.006821,NaN,0.051150,-0.008328,0.009252,-0.002857,0.022981,0.016790,...,-0.031385,-0.052410,0.006484,-0.016552,0.004501,0.068199,-0.000889,-0.009527,NaN,NaN
2025-03-11,0.022394,0.000936,0.003761,NaN,0.023308,-0.017088,0.024516,0.009715,0.030374,0.022425,...,0.003084,-0.006083,0.000904,-0.000137,0.015431,0.020377,0.005057,0.009034,-0.011152,-0.014522
2025-03-12,0.029128,-0.002329,-0.015120,NaN,-0.021368,-0.015184,-0.002276,-0.002015,-0.005214,0.010833,...,-0.038902,-0.014290,-0.022344,0.000536,0.012856,-0.038950,-0.008314,0.014989,0.080642,0.020146
2025-03-13,0.003700,0.007696,-0.008214,NaN,-0.020358,-0.000309,-0.023932,-0.002838,-0.019983,-0.000324,...,-0.037108,-0.016564,-0.011060,-0.004815,-0.007678,-0.028544,-0.013323,0.009001,0.018835,-0.005003

In [3]:
label_ = pd.read_feather("/home/datamake117/test0121/label.fea")  # 使用不调整的label构造相关性矩阵
label_['index'] = pd.to_datetime(label_['index'])
label_ = label_.set_index('index', drop=True)
label_  # 1487 rows × 5313 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,603072,301458,688758,301601,688583,301602,688545,001356,001395,688411
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-17,0.036108,-0.011673,-0.024936,NaN,-0.035973,-0.002923,0.006975,0.001263,0.007515,-0.011201,...,-0.016786,0.020283,-0.009496,0.030848,0.041144,-0.117492,-0.002017,-0.010027,0.021765,0.072311
2025-02-18,-0.003439,0.002122,-0.038403,NaN,-0.055684,-0.009729,0.065561,-0.009288,-0.036602,-0.031783,...,-0.004224,-0.009457,0.009067,0.013057,0.039335,0.000813,0.027549,-0.030393,0.002818,-0.047289
2025-02-19,-0.031868,-0.017337,-0.028318,NaN,-0.003512,-0.016959,0.058063,-0.024570,-0.012861,-0.012748,...,0.028597,0.030011,-0.007117,-0.030681,0.028595,0.033231,0.049339,-0.009110,-0.004095,-0.034555
2025-02-20,-0.025020,-0.015089,-0.000791,NaN,-0.017536,-0.032720,-0.049042,-0.024724,-0.008328,-0.029820,...,-0.022281,0.010653,-0.022839,-0.042764,-0.032462,-0.025765,0.007519,-0.020477,-0.043670,-0.031407
2025-02-21,-0.023229,0.023838,-0.040590,NaN,-0.065621,-0.019193,0.002747,-0.003207,0.031588,-0.012277,...,-0.009934,-0.021161,-0.029788,-0.027044,-0.033594,0.006935,-0.004401,-0.009599,-0.018433,-0.019947

# 读取特征
## 读取特征0（1250个）

In [ ]:
year = 2020
os.chdir(r"/home/datamake117/test0121/feature0")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor1 = pd.concat(factor_list)
factor1  # 5398930 rows × 1252 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/1243 [00:00<?, ?it/s]

## 读取特征1（1540个）

In [ ]:
year = 2020
os.chdir(r"/home/datamake117/test0121/feature1")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor2 = pd.concat(factor_list)
factor2.columns = ['date', 'Code'] + [str(i) for i in range((len(factor1.columns) - 2), ((len(factor1.columns) - 2) + (len(factor2.columns) - 2)))]
factor2  # 5398930 rows × 1542 columns (index: 2020-01-02 - 2024-12-31)

## 合并全部特征（2790个）

In [ ]:
total_factor = pd.merge(factor1, factor2, how='inner', on=['date', 'Code'])
total_factor  # 5398930 rows × 2792 columns (index: 2020-01-02 - 2024-12-31)

# 合并特征和标签

In [ ]:
def look(date, Code):
    try:
        return label.loc[str(date), Code]
    except:
        return None
    
def look_(date, Code):
    try:
        return label_.loc[str(date), Code]
    except:
        return None

total_factor['label'] = [look(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['label_'] = [look_(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['date'] = total_factor['date'].astype("datetime64[ns]")
total_factor  # 5398930 rows × 2794 columns (index: 2020-01-02 - 2024-12-31)

# 增加可成交量变量

In [ ]:
total_factor['qcut'] = 0
total_factor['weight'] = 0
total_factor['qid'] = 0

daily_amount = pd.read_feather(r"/home/datamake117/test0121/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')
lookup_dict = daily_amount.stack().to_dict()
total_factor['amount'] = total_factor.set_index(['date', 'Code']).index.map(lookup_dict)
total_factor.to_pickle('/home/datamake117/data/haris/dataset_new/total_factor.pkl')  # 因子+标签
total_factor  # 5398930 rows × 2798 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
# 设置两级索引，第一级为日期，第二级为股票代码
total_factor.set_index(["date", "Code"], inplace=True)
total_factor.sort_index(level=["date", "Code"], inplace=True)

# 重建 DataFrame，使每个日期的股票数相同，缺失值用 NaN 补充
all_dates = total_factor.index.get_level_values("date").unique()
all_stocks = total_factor.index.get_level_values("Code").unique()
full_index = pd.MultiIndex.from_product([all_dates, all_stocks], names=["date", "Code"])
total_factor = total_factor.reindex(full_index)
total_factor.sort_index(level=["date", "Code"], inplace=True)
total_factor.columns = [str(i) for i in range(2790)] + ['label', 'label_', 'qcut', 'weight', 'qid', 'amount']
total_factor.index = total_factor.index.set_levels(total_factor.index.levels[0].strftime("%Y%m%d").astype(int), level='date')
total_factor  # 6354516 rows × 2796 columns (index: 2020-01-02 - 2024-12-31)

# 保存数据

In [ ]:
grouped = total_factor[[str(i) for i in range(2790)]]
grouped.to_pickle('/home/datamake117/data/haris/dataset_new/grouped_adj.pkl')  # 仅因子
grouped  # 6354516 rows × 2790 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
grouped_label = total_factor[['label', 'qcut', 'weight', 'qid', 'amount']]
grouped_label.to_pickle('/home/datamake117/data/haris/dataset_new/grouped_label_adj.pkl')  # 仅标签
grouped_label  # 6354516 rows × 5 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
daily_amount = pd.read_feather(r"/home/datamake117/test0121/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')

daily_amount_shift = daily_amount
intersection = [col for col in list(grouped_label.loc[20200701].index) if col in daily_amount_shift.columns]
daily_amount_shift = daily_amount_shift[intersection]
daily_amount_shift = daily_amount_shift.fillna(0)
daily_amount_shift.to_pickle('/home/datamake117/data/haris/dataset_new/grouped_liquidity.pkl')  # 流动性指标
daily_amount_shift  # 1487 rows × 5243 columns (index: 2019-01-02 - 2025-02-21)

In [ ]:
temp = grouped_label.reset_index()[['date', 'Code']]
temp.to_pickle('/home/datamake117/data/haris/dataset_new/total_date.pkl')  # 日期+股票代码
temp  # 6354516 rows × 2 columns