In [2]:
import os
import pandas as pd
from tqdm.notebook import tqdm
from datetime import datetime

# 读取标签

In [2]:
label = pd.read_feather("/home/datamake117/test1031/label.fea")
label['index'] = pd.to_datetime(label['index'])
label = label.set_index('index', drop=True)
label  # 1494 rows × 5314 columns (index: 2019-01-02 - 2025-03-04)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,301501,603124,001382,301629,688757,301535,301616,301658,603257,603210
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11,-0.009464,-0.026204,-0.000854,NaN,0.039924,0.059154,0.015116,0.024180,-0.007172,0.000225,...,0.020336,0.089652,0.043167,0.055883,0.111713,0.063756,0.058567,0.007598,NaN,NaN
2025-04-14,-0.003801,-0.013716,0.111416,NaN,0.004225,0.004560,-0.030557,-0.003801,0.027087,-0.001276,...,0.038393,0.020496,0.121079,-0.020958,-0.009357,0.068325,0.033359,-0.024709,NaN,NaN
2025-04-15,0.019814,0.012488,0.054200,NaN,-0.012788,-0.024549,-0.056819,-0.005034,-0.006892,-0.001296,...,0.062212,0.018647,0.062960,-0.035958,-0.026035,0.042201,-0.020921,-0.025667,0.017288,NaN
2025-04-16,0.020019,0.039644,0.020933,NaN,0.009731,0.018092,-0.023233,-0.002105,-0.037329,0.016942,...,0.021988,-0.031856,0.011211,-0.003272,-0.026316,0.018424,-0.037046,-0.009069,-0.073777,-0.059207
2025-04-17,0.020311,0.040617,0.026138,NaN,0.048246,0.034600,-0.039980,-0.008376,0.015306,0.049306,...,0.015382,0.008122,0.047832,0.015389,-0.009585,-0.024998,0.025894,-0.023771,-0.159312,-0.026098

In [3]:
label_ = pd.read_feather("/home/datamake117/test1031/label.fea")  # 使用不调整的label构造相关性矩阵
label_['index'] = pd.to_datetime(label_['index'])
label_ = label_.set_index('index', drop=True)
label_  # 1487 rows × 5313 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,301501,603124,001382,301629,688757,301535,301616,301658,603257,603210
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11,-0.009464,-0.026204,-0.000854,NaN,0.039924,0.059154,0.015116,0.024180,-0.007172,0.000225,...,0.020336,0.089652,0.043167,0.055883,0.111713,0.063756,0.058567,0.007598,NaN,NaN
2025-04-14,-0.003801,-0.013716,0.111416,NaN,0.004225,0.004560,-0.030557,-0.003801,0.027087,-0.001276,...,0.038393,0.020496,0.121079,-0.020958,-0.009357,0.068325,0.033359,-0.024709,NaN,NaN
2025-04-15,0.019814,0.012488,0.054200,NaN,-0.012788,-0.024549,-0.056819,-0.005034,-0.006892,-0.001296,...,0.062212,0.018647,0.062960,-0.035958,-0.026035,0.042201,-0.020921,-0.025667,0.017288,NaN
2025-04-16,0.020019,0.039644,0.020933,NaN,0.009731,0.018092,-0.023233,-0.002105,-0.037329,0.016942,...,0.021988,-0.031856,0.011211,-0.003272,-0.026316,0.018424,-0.037046,-0.009069,-0.073777,-0.059207
2025-04-17,0.020311,0.040617,0.026138,NaN,0.048246,0.034600,-0.039980,-0.008376,0.015306,0.049306,...,0.015382,0.008122,0.047832,0.015389,-0.009585,-0.024998,0.025894,-0.023771,-0.159312,-0.026098

# 读取特征
## 读取特征0（1250个）

In [4]:
year = 2020
os.chdir(r"/home/datamake117/test1031/feature0")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor1 = pd.concat(factor_list)
factor1  # 5398930 rows × 1252 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/1282 [00:00<?, ?it/s]

,date,Code,0,1,2,3,4,5,6,7,...,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249
0,2020-01-02,000001,0.142429,0.708937,0.087276,2.361127,1.447166,3.621611,1.259786,2.349505,...,0.014142,0.074876,0.033301,0.050662,0.063640,0.035355,0.028284,0.014142,0.014142,0.014142
1,2020-01-02,000002,0.232188,0.553838,-0.052696,0.143417,0.795705,-4.398874,0.732794,0.148938,...,-0.007071,-0.099301,-0.065184,-0.065184,-0.079073,-0.028251,-0.030000,-0.030000,-0.007071,-0.007071
2,2020-01-02,000004,0.129032,0.902306,-0.089413,-3.294483,0.073779,-4.185775,0.243243,-3.187878,...,0.000000,-0.412997,-0.412997,-0.412997,-0.304138,-0.275379,-0.229420,-0.149332,-0.028284,0.000000
3,2020-01-02,000005,0.003936,0.962999,0.011201,-2.758275,1.244934,-4.228945,0.402985,-2.640067,...,0.000000,-0.012910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2020-01-02,000006,0.059158,0.808410,-0.066815,0.230044,0.572983,-3.184859,0.476190,0.285741,...,0.000000,-0.049497,-0.014142,-0.014142,-0.014142,-0.014142,-0.014142,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954,2025-04-18,688799,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4955,2025-04-18,688800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4956,2025-04-18,688819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4957,2025-04-18,688981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4958,2025-04-18,689009,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## 读取特征1（1540个）

In [5]:
year = 2020
os.chdir(r"/home/datamake117/test1031/feature1")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor2 = pd.concat(factor_list)
factor2.columns = ['date', 'Code'] + [str(i) for i in range((len(factor1.columns) - 2), ((len(factor1.columns) - 2) + (len(factor2.columns) - 2)))]
factor2  # 5398930 rows × 1542 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/1282 [00:00<?, ?it/s]

,date,Code,1250,1251,1252,1253,1254,1255,1256,1257,...,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789
0,2020-01-02,000001,-0.000371,0.144566,0.167514,0.030235,-0.043070,0.358179,1.350860,0.139044,...,0.0,0.0,0.0,0.0,-1.0,10500.0,70.0,1.0,0.100181,0.0
1,2020-01-02,000002,0.000338,0.150542,0.113075,0.056990,0.026726,0.505274,1.306157,0.319926,...,0.0,0.0,0.0,0.0,-1.0,10564.0,67.0,1.0,0.100095,0.0
2,2020-01-02,000004,-0.000049,0.131501,0.216560,-0.000914,-0.087498,0.387429,2.045524,0.131223,...,0.0,0.0,0.0,0.0,-1.0,10579.0,61.0,0.0,0.100044,0.0
3,2020-01-02,000005,0.000024,0.168856,0.170853,0.016271,0.002746,0.417996,1.513899,0.215653,...,0.0,0.0,0.0,0.0,-1.0,10605.0,62.0,0.0,0.100649,0.0
4,2020-01-02,000006,-0.000474,0.141803,0.150814,-0.003795,0.018822,0.384158,1.462300,0.175712,...,0.0,0.0,0.0,0.0,-1.0,10110.0,62.0,1.0,0.099624,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954,2025-04-18,688799,-0.002790,0.134127,0.142278,0.002626,0.009336,0.006464,0.234733,0.006464,...,0.0,0.0,0.0,0.0,2.0,1375.0,170.0,1.0,0.199947,0.0
4955,2025-04-18,688800,-0.000020,0.158325,0.183759,-0.029363,-0.002554,0.388064,1.645328,0.235089,...,0.0,0.0,0.0,0.0,2.0,1366.0,2.0,1.0,0.200093,0.0
4956,2025-04-18,688819,0.000162,0.147416,0.187278,-0.000790,-0.006294,0.383152,1.830792,0.180029,...,0.0,0.0,0.0,0.0,2.0,1551.0,20.0,1.0,0.200080,0.0
4957,2025-04-18,688981,-0.000198,0.157071,0.184334,-0.038100,-0.030389,0.401831,1.054973,0.241801,...,0.0,0.0,0.0,0.0,2.0,1737.0,20.0,1.0,0.200000,0.0
4958,2025-04-18,689009,-0.000273,0.171283,0.177224,-0.069400,0.001695,0.403795,1.223020,0.210946,...,0.0,0.0,0.0,0.0,2.0,1632.0,5.0,1.0,0.200000,0.0

## 合并全部特征（2790个）

In [6]:
total_factor = pd.merge(factor1, factor2, how='inner', on=['date', 'Code'])
total_factor  # 5398930 rows × 2792 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789
0,2020-01-02,000001,0.142429,0.708937,0.087276,2.361127,1.447166,3.621611,1.259786,2.349505,...,0.0,0.0,0.0,0.0,-1.0,10500.0,70.0,1.0,0.100181,0.0
1,2020-01-02,000002,0.232188,0.553838,-0.052696,0.143417,0.795705,-4.398874,0.732794,0.148938,...,0.0,0.0,0.0,0.0,-1.0,10564.0,67.0,1.0,0.100095,0.0
2,2020-01-02,000004,0.129032,0.902306,-0.089413,-3.294483,0.073779,-4.185775,0.243243,-3.187878,...,0.0,0.0,0.0,0.0,-1.0,10579.0,61.0,0.0,0.100044,0.0
3,2020-01-02,000005,0.003936,0.962999,0.011201,-2.758275,1.244934,-4.228945,0.402985,-2.640067,...,0.0,0.0,0.0,0.0,-1.0,10605.0,62.0,0.0,0.100649,0.0
4,2020-01-02,000006,0.059158,0.808410,-0.066815,0.230044,0.572983,-3.184859,0.476190,0.285741,...,0.0,0.0,0.0,0.0,-1.0,10110.0,62.0,1.0,0.099624,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746691,2025-04-18,688799,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,2.0,1375.0,170.0,1.0,0.199947,0.0
5746692,2025-04-18,688800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,2.0,1366.0,2.0,1.0,0.200093,0.0
5746693,2025-04-18,688819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,2.0,1551.0,20.0,1.0,0.200080,0.0
5746694,2025-04-18,688981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,2.0,1737.0,20.0,1.0,0.200000,0.0
5746695,2025-04-18,689009,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,2.0,1632.0,5.0,1.0,0.200000,0.0

# 合并特征和标签

In [7]:
def look(date, Code):
    try:
        return label.loc[str(date), Code]
    except:
        return None
    
def look_(date, Code):
    try:
        return label_.loc[str(date), Code]
    except:
        return None

total_factor['label'] = [look(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['label_'] = [look_(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['date'] = total_factor['date'].astype("datetime64[ns]")
total_factor  # 5398930 rows × 2794 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,2782,2783,2784,2785,2786,2787,2788,2789,label,label_
0,2020-01-02,000001,0.142429,0.708937,0.087276,2.361127,1.447166,3.621611,1.259786,2.349505,...,0.0,0.0,-1.0,10500.0,70.0,1.0,0.100181,0.0,0.010385,0.010385
1,2020-01-02,000002,0.232188,0.553838,-0.052696,0.143417,0.795705,-4.398874,0.732794,0.148938,...,0.0,0.0,-1.0,10564.0,67.0,1.0,0.100095,0.0,-0.044313,-0.044313
2,2020-01-02,000004,0.129032,0.902306,-0.089413,-3.294483,0.073779,-4.185775,0.243243,-3.187878,...,0.0,0.0,-1.0,10579.0,61.0,0.0,0.100044,0.0,-0.034692,-0.034692
3,2020-01-02,000005,0.003936,0.962999,0.011201,-2.758275,1.244934,-4.228945,0.402985,-2.640067,...,0.0,0.0,-1.0,10605.0,62.0,0.0,0.100649,0.0,-0.008585,-0.008585
4,2020-01-02,000006,0.059158,0.808410,-0.066815,0.230044,0.572983,-3.184859,0.476190,0.285741,...,0.0,0.0,-1.0,10110.0,62.0,1.0,0.099624,0.0,-0.012239,-0.012239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746691,2025-04-18,688799,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,2.0,1375.0,170.0,1.0,0.199947,0.0,NaN,NaN
5746692,2025-04-18,688800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,2.0,1366.0,2.0,1.0,0.200093,0.0,NaN,NaN
5746693,2025-04-18,688819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,2.0,1551.0,20.0,1.0,0.200080,0.0,NaN,NaN
5746694,2025-04-18,688981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,2.0,1737.0,20.0,1.0,0.200000,0.0,NaN,NaN
5746695,2025-04-18,689009,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,2.0,1632.0,5.0,1.0,0.200000,0.0,NaN,NaN

# 增加可成交量变量

In [9]:
total_factor['qcut'] = 0
total_factor['weight'] = 0
total_factor['qid'] = 0

daily_amount = pd.read_feather(r"/home/datamake117/test1031/can_trade_amt_500.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')
lookup_dict = daily_amount.stack().to_dict()
total_factor['amount'] = total_factor.set_index(['date', 'Code']).index.map(lookup_dict)
total_factor.to_pickle('/home/datamake117/data/haris/dataset_1031/total_factor.pkl')  # 因子+标签
total_factor  # 5398930 rows × 2798 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,2786,2787,2788,2789,label,label_,qcut,weight,qid,amount
0,2020-01-02,000001,0.142429,0.708937,0.087276,2.361127,1.447166,3.621611,1.259786,2.349505,...,70.0,1.0,0.100181,0.0,0.010385,0.010385,0,0,0,10000000.0
1,2020-01-02,000002,0.232188,0.553838,-0.052696,0.143417,0.795705,-4.398874,0.732794,0.148938,...,67.0,1.0,0.100095,0.0,-0.044313,-0.044313,0,0,0,10000000.0
2,2020-01-02,000004,0.129032,0.902306,-0.089413,-3.294483,0.073779,-4.185775,0.243243,-3.187878,...,61.0,0.0,0.100044,0.0,-0.034692,-0.034692,0,0,0,16987.5
3,2020-01-02,000005,0.003936,0.962999,0.011201,-2.758275,1.244934,-4.228945,0.402985,-2.640067,...,62.0,0.0,0.100649,0.0,-0.008585,-0.008585,0,0,0,64750.2
4,2020-01-02,000006,0.059158,0.808410,-0.066815,0.230044,0.572983,-3.184859,0.476190,0.285741,...,62.0,1.0,0.099624,0.0,-0.012239,-0.012239,0,0,0,169090.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746691,2025-04-18,688799,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,170.0,1.0,0.199947,0.0,NaN,NaN,0,0,0,NaN
5746692,2025-04-18,688800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.0,1.0,0.200093,0.0,NaN,NaN,0,0,0,NaN
5746693,2025-04-18,688819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,20.0,1.0,0.200080,0.0,NaN,NaN,0,0,0,NaN
5746694,2025-04-18,688981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,20.0,1.0,0.200000,0.0,NaN,NaN,0,0,0,NaN
5746695,2025-04-18,689009,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.0,1.0,0.200000,0.0,NaN,NaN,0,0,0,NaN

In [10]:
# 设置两级索引，第一级为日期，第二级为股票代码
total_factor.set_index(["date", "Code"], inplace=True)
total_factor.sort_index(level=["date", "Code"], inplace=True)

# 重建 DataFrame，使每个日期的股票数相同，缺失值用 NaN 补充
all_dates = total_factor.index.get_level_values("date").unique()
all_stocks = total_factor.index.get_level_values("Code").unique()
full_index = pd.MultiIndex.from_product([all_dates, all_stocks], names=["date", "Code"])
total_factor = total_factor.reindex(full_index)
total_factor.sort_index(level=["date", "Code"], inplace=True)
total_factor.columns = [str(i) for i in range(2790)] + ['label', 'label_', 'qcut', 'weight', 'qid', 'amount']
total_factor.index = total_factor.index.set_levels(total_factor.index.levels[0].strftime("%Y%m%d").astype(int), level='date')
total_factor  # 6354516 rows × 2796 columns (index: 2020-01-02 - 2024-12-31)

                        0         1         2         3         4         5  \
date     Code
20200102 000001  0.142429  0.708937  0.087276  2.361127  1.447166  3.621611
         000002  0.232188  0.553838 -0.052696  0.143417  0.795705 -4.398874
         000004  0.129032  0.902306 -0.089413 -3.294483  0.073779 -4.185775
         000005  0.003936  0.962999  0.011201 -2.758275  1.244934 -4.228945
         000006  0.059158  0.808410 -0.066815  0.230044  0.572983 -3.184859
...                   ...       ...       ...       ...       ...       ...
20250418 688799  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688800  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688819  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688981  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         689009  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

                        6         7         8         9  ...   2786  2787  \
date     Code                                            ...
20200102 000001  1.259786  2.349505  1.479921  1.517300  ...   70.0   1.0
         000002  0.732794  0.148938  0.805419  0.837959  ...   67.0   1.0
         000004  0.243243 -3.187878  0.080566  0.081017  ...   61.0   0.0
         000005  0.402985 -2.640067  1.323399  1.341368  ...   62.0   0.0
         000006  0.476190  0.285741  0.606940  0.623770  ...   62.0   1.0
...                   ...       ...       ...       ...  ...    ...   ...
20250418 688799  0.000000  0.000000  0.000000  0.000000  ...  170.0   1.0
         688800  0.000000  0.000000  0.000000  0.000000  ...    2.0   1.0
         688819  0.000000  0.000000  0.000000  0.000000  ...   20.0   1.0
         688981  0.000000  0.000000  0.000000  0.000000  ...   20.0   1.0
         689009  0.000000  0.000000  0.000000  0.000000  ...    5.0   1.0

                     2788  2789     label    label_  qcut  weight  qid  \
date     Code
20200102 000001  0.100181   0.0  0.010385  0.010385   0.0     0.0  0.0
         000002  0.100095   0.0 -0.044313 -0.044313   0.0     0.0  0.0
         000004  0.100044   0.0 -0.034692 -0.034692   0.0     0.0  0.0
         000005  0.100649   0.0 -0.008585 -0.008585   0.0     0.0  0.0
         000006  0.099624   0.0 -0.012239 -0.012239   0.0     0.0  0.0
...                   ...   ...       ...       ...   ...     ...  ...
20250418 688799  0.199947   0.0       NaN       NaN   0.0     0.0  0.0
         688800  0.200093   0.0       NaN       NaN   0.0     0.0  0.0
         688819  0.200080   0.0       NaN       NaN   0.0     0.0  0.0
         688981  0.200000   0.0       NaN       NaN   0.0     0.0  0.0
         689009  0.200000   0.0       NaN       NaN   0.0     0.0  0.0

                     amount
date     Code
20200102 000001  10000000.0
         000002  10000000.0
         000004     16987.5
         000005     64750.2
         000006    169090.2
...                     ...
20250418 688799         NaN
         688800         NaN
         688819         NaN
         688981         NaN
         689009         NaN

[6759986 rows x 2796 columns]

# 保存数据

In [11]:
grouped = total_factor[[str(i) for i in range(2790)]]
grouped.to_pickle('/home/datamake117/data/haris/dataset_1031/grouped_adj.pkl')  # 仅因子
grouped  # 6354516 rows × 2790 columns (index: 2020-01-02 - 2024-12-31)

                        0         1         2         3         4         5  \
date     Code
20200102 000001  0.142429  0.708937  0.087276  2.361127  1.447166  3.621611
         000002  0.232188  0.553838 -0.052696  0.143417  0.795705 -4.398874
         000004  0.129032  0.902306 -0.089413 -3.294483  0.073779 -4.185775
         000005  0.003936  0.962999  0.011201 -2.758275  1.244934 -4.228945
         000006  0.059158  0.808410 -0.066815  0.230044  0.572983 -3.184859
...                   ...       ...       ...       ...       ...       ...
20250418 688799  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688800  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688819  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688981  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         689009  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

                        6         7         8         9  ...  2780  2781  \
date     Code                                            ...
20200102 000001  1.259786  2.349505  1.479921  1.517300  ...   0.0   0.0
         000002  0.732794  0.148938  0.805419  0.837959  ...   0.0   0.0
         000004  0.243243 -3.187878  0.080566  0.081017  ...   0.0   0.0
         000005  0.402985 -2.640067  1.323399  1.341368  ...   0.0   0.0
         000006  0.476190  0.285741  0.606940  0.623770  ...   0.0   0.0
...                   ...       ...       ...       ...  ...   ...   ...
20250418 688799  0.000000  0.000000  0.000000  0.000000  ...   0.0   0.0
         688800  0.000000  0.000000  0.000000  0.000000  ...   0.0   0.0
         688819  0.000000  0.000000  0.000000  0.000000  ...   0.0   0.0
         688981  0.000000  0.000000  0.000000  0.000000  ...   0.0   0.0
         689009  0.000000  0.000000  0.000000  0.000000  ...   0.0   0.0

                 2782  2783  2784     2785   2786  2787      2788  2789
date     Code
20200102 000001   0.0   0.0  -1.0  10500.0   70.0   1.0  0.100181   0.0
         000002   0.0   0.0  -1.0  10564.0   67.0   1.0  0.100095   0.0
         000004   0.0   0.0  -1.0  10579.0   61.0   0.0  0.100044   0.0
         000005   0.0   0.0  -1.0  10605.0   62.0   0.0  0.100649   0.0
         000006   0.0   0.0  -1.0  10110.0   62.0   1.0  0.099624   0.0
...               ...   ...   ...      ...    ...   ...       ...   ...
20250418 688799   0.0   0.0   2.0   1375.0  170.0   1.0  0.199947   0.0
         688800   0.0   0.0   2.0   1366.0    2.0   1.0  0.200093   0.0
         688819   0.0   0.0   2.0   1551.0   20.0   1.0  0.200080   0.0
         688981   0.0   0.0   2.0   1737.0   20.0   1.0  0.200000   0.0
         689009   0.0   0.0   2.0   1632.0    5.0   1.0  0.200000   0.0

[6759986 rows x 2790 columns]

In [12]:
grouped_label = total_factor[['label', 'qcut', 'weight', 'qid', 'amount']]
grouped_label.to_pickle('/home/datamake117/data/haris/dataset_1031/grouped_label_adj.pkl')  # 仅标签
grouped_label  # 6354516 rows × 5 columns (index: 2020-01-02 - 2024-12-31)

                    label  qcut  weight  qid      amount
date     Code
20200102 000001  0.010385   0.0     0.0  0.0  10000000.0
         000002 -0.044313   0.0     0.0  0.0  10000000.0
         000004 -0.034692   0.0     0.0  0.0     16987.5
         000005 -0.008585   0.0     0.0  0.0     64750.2
         000006 -0.012239   0.0     0.0  0.0    169090.2
...                   ...   ...     ...  ...         ...
20250418 688799       NaN   0.0     0.0  0.0         NaN
         688800       NaN   0.0     0.0  0.0         NaN
         688819       NaN   0.0     0.0  0.0         NaN
         688981       NaN   0.0     0.0  0.0         NaN
         689009       NaN   0.0     0.0  0.0         NaN

[6759986 rows x 5 columns]

In [ ]:
daily_amount = pd.read_feather(r"/home/datamake117/test1031/can_trade_amt_500.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')

daily_amount_shift = daily_amount
intersection = [col for col in list(grouped_label.loc[20200701].index) if col in daily_amount_shift.columns]
daily_amount_shift = daily_amount_shift[intersection]
daily_amount_shift = daily_amount_shift.fillna(0)
daily_amount_shift.to_pickle('/home/datamake117/data/haris/dataset_1031/grouped_liquidity.pkl')  # 流动性指标
daily_amount_shift  # 1487 rows × 5243 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688787,688788,688789,688793,688798,688799,688800,688819,688981,689009
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,1097221.50,931650.531,0.0,4035.0,5128.2,84766.5,95227.2,138982.5,12675.0,11316.0,...,0.000,0.00,0.000,0.000,0.000,0.00,0.000,0.000,0.00,0.000
2019-01-03,830523.78,152731.800,481.8,3698.4,3399.0,77714.1,10681.2,22470.0,22404.9,558.6,...,0.000,0.00,0.000,0.000,0.000,0.00,0.000,0.000,0.00,0.000
2019-01-04,1048647.60,435401.100,2934.0,3123.9,20309.1,140454.0,97812.0,38304.0,16039.2,51670.8,...,0.000,0.00,0.000,0.000,0.000,0.00,0.000,0.000,0.00,0.000
2019-01-07,7300591.20,6348042.900,26908.2,39281.4,371718.0,154982.1,284163.0,133830.3,10289.7,120059.1,...,0.000,0.00,0.000,0.000,0.000,0.00,0.000,0.000,0.00,0.000
2019-01-08,894381.60,1057104.990,8721.0,16443.6,110791.2,235467.0,372771.3,7626.6,5406.0,37286.4,...,0.000,0.00,0.000,0.000,0.000,0.00,0.000,0.000,0.00,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-11,1951382.40,4526979.600,150696.0,0.0,812251.5,91176.0,3748563.0,140407.8,34483.2,31717.8,...,605959.200,163388.40,388098.360,165901.161,237375.000,0.00,364901.196,87016.965,7611796.50,369090.480
2025-04-14,3966164.46,2294429.400,77280.0,0.0,691156.2,33189.0,3373527.3,197584.5,122532.9,12117.6,...,228598.434,49500.00,118227.705,31457.400,2527870.092,64487.82,481720.140,59621.928,10000000.00,1992310.125
2025-04-15,907779.60,738144.000,62551.5,0.0,260922.6,243307.8,2322676.8,107385.6,6966.0,28249.2,...,522727.884,25367.04,40576.800,35338.212,128131.080,16902.00,683343.000,34983.783,3377588.22,162534.444
2025-04-16,2080525.50,704421.600,956130.0,0.0,367071.6,102942.0,1196876.1,78825.6,216453.6,14530.2,...,324038.412,50886.00,19920.600,66157.476,51848.595,16663.50,173830.110,0.000,6157788.00,167364.288
2025-04-17,2433528.00,1127341.800,373840.2,0.0,269781.3,14458.5,722484.0,26944.5,61275.0,19656.0,...,10054.800,4587.90,29382.984,138560.301,105252.000,0.00,92782.629,2983.200,3984505.47,193107.000

In [15]:
temp = grouped_label.reset_index()[['date', 'Code']]
temp.to_pickle('/home/datamake117/data/haris/dataset_1031/total_date.pkl')  # 日期+股票代码
temp  # 6354516 rows × 2 columns

             date    Code
0        20200102  000001
1        20200102  000002
2        20200102  000004
3        20200102  000005
4        20200102  000006
...           ...     ...
6759981  20250418  688799
6759982  20250418  688800
6759983  20250418  688819
6759984  20250418  688981
6759985  20250418  689009

[6759986 rows x 2 columns]

FileNotFoundError: [Errno 2] No such file or directory: '/home/datamake117/test1031/can_trade_amt_500.fea'