In [1]:
import os
import pandas as pd
from tqdm.notebook import tqdm
from datetime import datetime

# 读取标签

In [2]:
label = pd.read_feather("/home/datamake117/test0326/label_divide1_5.fea")
label['index'] = pd.to_datetime(label['index'])
label = label.set_index('index', drop=True)
label  # 1508 rows × 5319 columns (index: 2019-01-02 - 2025-03-04)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688545,001356,001395,688411,302132,301173,301557,603409,301275,603271
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-18,0.001077,-0.012133,-0.033516,NaN,-0.011062,-0.017556,-0.013057,-0.012747,-0.015156,-0.003617,...,-0.005561,-0.006015,0.011120,-0.049351,-0.009488,0.031885,0.009257,0.003586,0.068445,0.001077
2025-03-19,0.012906,0.004025,-0.008440,NaN,0.004378,-0.005125,0.015594,-0.001854,0.015303,0.025053,...,-0.016574,0.005652,0.047912,-0.029240,0.010294,0.006525,0.003670,0.000788,-0.061038,-0.008373
2025-03-20,0.013406,0.009145,-0.007131,NaN,0.061226,0.008607,0.017628,0.009543,0.047716,0.030704,...,-0.006467,0.007654,-0.003147,0.030435,0.015961,-0.009836,0.020693,-0.010425,0.002227,-0.020137
2025-03-21,0.005346,-0.014810,-0.106419,NaN,0.019571,-0.029666,-0.042020,-0.000338,0.011673,-0.008637,...,0.008192,-0.020080,-0.006916,0.001947,0.004032,-0.003046,-0.014061,-0.028481,0.004585,-0.037776
2025-03-24,0.005936,-0.017586,-0.074883,NaN,-0.003428,-0.027766,-0.032049,0.007725,-0.005621,-0.010018,...,0.010481,-0.025399,0.031853,-0.027389,0.001639,-0.000118,-0.019829,-0.004155,-0.046722,-0.008285

In [3]:
label_ = pd.read_feather("/home/datamake117/test0326/label.fea")  # 使用不调整的label构造相关性矩阵
label_['index'] = pd.to_datetime(label_['index'])
label_ = label_.set_index('index', drop=True)
label_  # 1508 rows × 5319 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688545,001356,001395,688411,302132,301173,301557,603409,301275,603271
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-18,0.001077,-0.012133,-0.033516,NaN,-0.011062,-0.017556,-0.013057,-0.012747,-0.015156,-0.003617,...,-0.010230,-0.006015,0.011120,-0.075915,-0.016120,0.045939,0.011997,0.003586,0.100779,0.001077
2025-03-19,0.012906,0.004025,-0.008440,NaN,0.004378,-0.005125,0.015594,-0.001854,0.015303,0.025053,...,-0.030673,0.005652,0.047912,-0.049672,0.009629,0.003975,-0.000308,0.000788,-0.097369,-0.008373
2025-03-20,0.013406,0.009145,-0.007131,NaN,0.061226,0.008607,0.017628,0.009543,0.047716,0.030704,...,-0.021816,0.007654,-0.003147,0.033538,0.011827,-0.026870,0.018924,-0.010425,-0.008774,-0.020137
2025-03-21,0.005346,-0.014810,-0.106419,NaN,0.019571,-0.029666,-0.042020,-0.000338,0.011673,-0.008637,...,-0.001080,-0.020080,-0.006916,-0.010447,-0.007320,-0.017936,-0.034460,-0.028481,-0.006490,-0.037776
2025-03-24,0.005936,-0.017586,-0.074883,NaN,-0.003428,-0.027766,-0.032049,0.007725,-0.005621,-0.010018,...,0.008318,-0.025399,0.031853,-0.048487,-0.004945,-0.007580,-0.037146,-0.004155,-0.077486,-0.008285

# 读取特征
## 读取特征0（1250个）

In [4]:
year = 2020
os.chdir(r"/home/datamake117/test0326/feature0")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor1 = pd.concat(factor_list)
factor1  # 5398930 rows × 1252 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/994 [00:00<?, ?it/s]

,date,Code,0,1,2,3,4,5,6,7,...,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249
0,2021-01-05,000001,0.071664,0.685760,-0.199404,-3.417535,0.258343,-5.388288,0.653179,-3.462629,...,0.000000,-0.035508,-0.031228,-0.031228,-0.036763,-0.040000,-0.036621,-0.049497,-0.007071,0.000000
1,2021-01-05,000002,0.033293,0.756402,-0.061616,-0.923554,0.642608,-3.592522,0.808333,-0.903918,...,0.000000,-0.014907,-0.012867,-0.012867,-0.013229,-0.017078,-0.017078,-0.020000,-0.007071,0.000000
2,2021-01-05,000004,0.041933,0.832400,-0.071108,-1.812693,0.475614,-1.823890,0.606061,-1.799145,...,0.000000,-0.310000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2021-01-05,000005,0.004317,0.958121,-0.026501,-1.706366,0.342068,-3.706094,0.241379,-1.712731,...,0.000000,-0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2021-01-05,000006,0.000206,0.971685,-0.013775,-2.612419,0.450552,-1.542106,0.620690,-2.554165,...,0.000000,-0.014142,-0.014142,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4948,2025-02-14,688799,0.013516,0.000000,0.000000,-1.230162,0.000000,-1.700521,0.000000,-1.153934,...,0.000000,-19.983724,-23.125766,-28.319627,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4949,2025-02-14,688800,0.381315,0.542528,-0.096741,0.441431,0.576844,1.263855,1.405405,0.448139,...,0.007071,0.399190,0.196886,0.196886,0.196886,0.084148,0.084148,0.080089,0.075807,0.062450
4950,2025-02-14,688819,0.041408,0.942160,-0.039829,-2.833302,0.272820,-2.098373,0.617021,-2.736076,...,0.000000,-18.989575,-20.300553,-12.008856,-12.008856,-0.042661,-0.045093,-0.045093,-0.035355,0.000000
4951,2025-02-14,688981,0.126986,0.732891,-0.078574,-2.118357,0.554371,6.505091,1.456559,-2.026053,...,-0.020817,-1.088967,-0.125359,-0.114782,-0.071034,-0.071034,-0.057886,-0.075719,-0.033615,-0.033615
4952,2025-02-14,689009,0.144818,0.704181,-0.050320,-0.095442,0.695665,1.524697,1.312500,-0.082578,...,0.000000,-0.491762,-0.129730,-0.122304,-0.144684,-0.169706,-0.169706,-0.084853,-0.084853,-0.084853

## 读取特征1（1799个）

In [5]:
year = 2020
os.chdir(r"/home/datamake117/test0326/feature1")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor2 = pd.concat(factor_list)
factor2.columns = ['date', 'Code'] + [str(i) for i in range((len(factor1.columns) - 2), ((len(factor1.columns) - 2) + (len(factor2.columns) - 2)))]
factor2  # 5398930 rows × 1542 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/994 [00:00<?, ?it/s]

,date,Code,1250,1251,1252,1253,1254,1255,1256,1257,...,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048
0,2021-01-05,000001,-0.000427,0.130824,0.176184,-0.151359,-0.060537,0.332923,1.159370,0.139248,...,0.936759,1.827603,1.958937,1.849779,1.808007,1.899696,1.800029,0.173608,1.884261,0.436159
1,2021-01-05,000002,0.000045,0.137174,0.185260,-0.029724,-0.058898,0.247764,0.939734,0.091328,...,0.936739,1.901046,1.963761,1.948429,1.807443,1.835787,1.959329,0.148608,1.831184,0.349514
2,2021-01-05,000004,-0.000038,0.172373,0.153303,0.023985,0.028314,0.310464,1.356313,0.168047,...,0.715285,0.681892,0.970457,0.567955,0.593723,0.456899,0.716246,1.154439,0.633216,1.046688
3,2021-01-05,000005,-0.000113,0.146888,0.166926,-0.007937,-0.060547,0.424189,2.270082,0.231171,...,0.015238,0.226351,0.646961,0.835797,0.000000,0.508222,0.191443,1.687688,0.614557,1.668922
4,2021-01-05,000006,0.000764,0.111641,0.185104,-0.052000,-0.092809,0.335166,1.429878,0.115458,...,0.245058,0.279683,0.761822,0.763092,0.375067,0.543365,0.496166,1.596688,0.538494,1.605645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4948,2025-02-14,688799,0.000092,0.145692,0.155581,-0.004441,-0.019759,0.563276,3.207983,0.134360,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4949,2025-02-14,688800,0.000693,0.142624,0.175458,-0.042594,-0.035371,0.445528,2.071052,0.188049,...,0.000000,0.000000,0.000000,0.000000,1.692345,0.000000,0.000000,0.000000,0.000000,0.000000
4950,2025-02-14,688819,-0.000107,0.176852,0.156727,-0.009723,0.013111,0.429413,1.946581,0.253491,...,0.000000,0.000000,0.000000,0.000000,1.178699,0.000000,0.000000,0.000000,0.000000,0.000000
4951,2025-02-14,688981,0.000044,0.169481,0.214044,-0.056680,-0.049816,0.389571,1.273317,0.190432,...,0.000000,0.000000,0.000000,0.000000,1.996996,0.000000,0.000000,0.000000,0.000000,0.000000
4952,2025-02-14,689009,-0.001113,0.159579,0.172010,0.036801,0.014638,0.353852,0.958725,0.266131,...,0.000000,0.000000,0.000000,0.000000,1.876587,0.000000,0.000000,0.000000,0.000000,0.000000

## 合并全部特征（3049个）

In [6]:
total_factor = pd.merge(factor1, factor2, how='inner', on=['date', 'Code'])
total_factor  # 5398930 rows × 2792 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048
0,2021-01-05,000001,0.071664,0.685760,-0.199404,-3.417535,0.258343,-5.388288,0.653179,-3.462629,...,0.936759,1.827603,1.958937,1.849779,1.808007,1.899696,1.800029,0.173608,1.884261,0.436159
1,2021-01-05,000002,0.033293,0.756402,-0.061616,-0.923554,0.642608,-3.592522,0.808333,-0.903918,...,0.936739,1.901046,1.963761,1.948429,1.807443,1.835787,1.959329,0.148608,1.831184,0.349514
2,2021-01-05,000004,0.041933,0.832400,-0.071108,-1.812693,0.475614,-1.823890,0.606061,-1.799145,...,0.715285,0.681892,0.970457,0.567955,0.593723,0.456899,0.716246,1.154439,0.633216,1.046688
3,2021-01-05,000005,0.004317,0.958121,-0.026501,-1.706366,0.342068,-3.706094,0.241379,-1.712731,...,0.015238,0.226351,0.646961,0.835797,0.000000,0.508222,0.191443,1.687688,0.614557,1.668922
4,2021-01-05,000006,0.000206,0.971685,-0.013775,-2.612419,0.450552,-1.542106,0.620690,-2.554165,...,0.245058,0.279683,0.761822,0.763092,0.375067,0.543365,0.496166,1.596688,0.538494,1.605645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4623284,2025-02-14,688799,0.013516,0.000000,0.000000,-1.230162,0.000000,-1.700521,0.000000,-1.153934,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4623285,2025-02-14,688800,0.381315,0.542528,-0.096741,0.441431,0.576844,1.263855,1.405405,0.448139,...,0.000000,0.000000,0.000000,0.000000,1.692345,0.000000,0.000000,0.000000,0.000000,0.000000
4623286,2025-02-14,688819,0.041408,0.942160,-0.039829,-2.833302,0.272820,-2.098373,0.617021,-2.736076,...,0.000000,0.000000,0.000000,0.000000,1.178699,0.000000,0.000000,0.000000,0.000000,0.000000
4623287,2025-02-14,688981,0.126986,0.732891,-0.078574,-2.118357,0.554371,6.505091,1.456559,-2.026053,...,0.000000,0.000000,0.000000,0.000000,1.996996,0.000000,0.000000,0.000000,0.000000,0.000000
4623288,2025-02-14,689009,0.144818,0.704181,-0.050320,-0.095442,0.695665,1.524697,1.312500,-0.082578,...,0.000000,0.000000,0.000000,0.000000,1.876587,0.000000,0.000000,0.000000,0.000000,0.000000

# 合并特征和标签

In [7]:
def look(date, Code):
    try:
        return label.loc[str(date), Code]
    except:
        return None
    
def look_(date, Code):
    try:
        return label_.loc[str(date), Code]
    except:
        return None

total_factor['label'] = [look(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['label_'] = [look_(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['date'] = total_factor['date'].astype("datetime64[ns]")
total_factor  # 5398930 rows × 2794 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,3041,3042,3043,3044,3045,3046,3047,3048,label,label_
0,2021-01-05,000001,0.071664,0.685760,-0.199404,-3.417535,0.258343,-5.388288,0.653179,-3.462629,...,1.958937,1.849779,1.808007,1.899696,1.800029,0.173608,1.884261,0.436159,0.056047,0.056047
1,2021-01-05,000002,0.033293,0.756402,-0.061616,-0.923554,0.642608,-3.592522,0.808333,-0.903918,...,1.963761,1.948429,1.807443,1.835787,1.959329,0.148608,1.831184,0.349514,0.027921,0.027921
2,2021-01-05,000004,0.041933,0.832400,-0.071108,-1.812693,0.475614,-1.823890,0.606061,-1.799145,...,0.970457,0.567955,0.593723,0.456899,0.716246,1.154439,0.633216,1.046688,-0.054570,-0.054570
3,2021-01-05,000005,0.004317,0.958121,-0.026501,-1.706366,0.342068,-3.706094,0.241379,-1.712731,...,0.646961,0.835797,0.000000,0.508222,0.191443,1.687688,0.614557,1.668922,-0.054615,-0.054615
4,2021-01-05,000006,0.000206,0.971685,-0.013775,-2.612419,0.450552,-1.542106,0.620690,-2.554165,...,0.761822,0.763092,0.375067,0.543365,0.496166,1.596688,0.538494,1.605645,-0.028815,-0.028815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4623284,2025-02-14,688799,0.013516,0.000000,0.000000,-1.230162,0.000000,-1.700521,0.000000,-1.153934,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.006603,-0.004346
4623285,2025-02-14,688800,0.381315,0.542528,-0.096741,0.441431,0.576844,1.263855,1.405405,0.448139,...,0.000000,0.000000,1.692345,0.000000,0.000000,0.000000,0.000000,0.000000,-0.007086,-0.005070
4623286,2025-02-14,688819,0.041408,0.942160,-0.039829,-2.833302,0.272820,-2.098373,0.617021,-2.736076,...,0.000000,0.000000,1.178699,0.000000,0.000000,0.000000,0.000000,0.000000,-0.005179,-0.002209
4623287,2025-02-14,688981,0.126986,0.732891,-0.078574,-2.118357,0.554371,6.505091,1.456559,-2.026053,...,0.000000,0.000000,1.996996,0.000000,0.000000,0.000000,0.000000,0.000000,-0.002473,0.001849
4623288,2025-02-14,689009,0.144818,0.704181,-0.050320,-0.095442,0.695665,1.524697,1.312500,-0.082578,...,0.000000,0.000000,1.876587,0.000000,0.000000,0.000000,0.000000,0.000000,0.055198,0.055198

# 增加可成交量变量

In [8]:
total_factor['qcut'] = 0
total_factor['weight'] = 0
total_factor['qid'] = 0

daily_amount = pd.read_feather(r"/home/datamake117/test0326/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')
lookup_dict = daily_amount.stack().to_dict()
total_factor['amount'] = total_factor.set_index(['date', 'Code']).index.map(lookup_dict)
total_factor.to_pickle('/home/datamake117/data/haris/dataset_0326/total_factor.pkl')  # 因子+标签
total_factor  # 5398930 rows × 2798 columns (index: 2020-01-02 - 2024-12-31)

,date,Code,0,1,2,3,4,5,6,7,...,3045,3046,3047,3048,label,label_,qcut,weight,qid,amount
0,2021-01-05,000001,0.071664,0.685760,-0.199404,-3.417535,0.258343,-5.388288,0.653179,-3.462629,...,1.800029,0.173608,1.884261,0.436159,0.056047,0.056047,0,0,0,5.037920e+06
1,2021-01-05,000002,0.033293,0.756402,-0.061616,-0.923554,0.642608,-3.592522,0.808333,-0.903918,...,1.959329,0.148608,1.831184,0.349514,0.027921,0.027921,0,0,0,1.114534e+07
2,2021-01-05,000004,0.041933,0.832400,-0.071108,-1.812693,0.475614,-1.823890,0.606061,-1.799145,...,0.716246,1.154439,0.633216,1.046688,-0.054570,-0.054570,0,0,0,1.849760e+05
3,2021-01-05,000005,0.004317,0.958121,-0.026501,-1.706366,0.342068,-3.706094,0.241379,-1.712731,...,0.191443,1.687688,0.614557,1.668922,-0.054615,-0.054615,0,0,0,3.843000e+04
4,2021-01-05,000006,0.000206,0.971685,-0.013775,-2.612419,0.450552,-1.542106,0.620690,-2.554165,...,0.496166,1.596688,0.538494,1.605645,-0.028815,-0.028815,0,0,0,3.630000e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4623284,2025-02-14,688799,0.013516,0.000000,0.000000,-1.230162,0.000000,-1.700521,0.000000,-1.153934,...,0.000000,0.000000,0.000000,0.000000,-0.006603,-0.004346,0,0,0,0.000000e+00
4623285,2025-02-14,688800,0.381315,0.542528,-0.096741,0.441431,0.576844,1.263855,1.405405,0.448139,...,0.000000,0.000000,0.000000,0.000000,-0.007086,-0.005070,0,0,0,1.025376e+06
4623286,2025-02-14,688819,0.041408,0.942160,-0.039829,-2.833302,0.272820,-2.098373,0.617021,-2.736076,...,0.000000,0.000000,0.000000,0.000000,-0.005179,-0.002209,0,0,0,5.956757e+04
4623287,2025-02-14,688981,0.126986,0.732891,-0.078574,-2.118357,0.554371,6.505091,1.456559,-2.026053,...,0.000000,0.000000,0.000000,0.000000,-0.002473,0.001849,0,0,0,2.000000e+07
4623288,2025-02-14,689009,0.144818,0.704181,-0.050320,-0.095442,0.695665,1.524697,1.312500,-0.082578,...,0.000000,0.000000,0.000000,0.000000,0.055198,0.055198,0,0,0,1.196299e+06

In [11]:
# 设置两级索引，第一级为日期，第二级为股票代码
total_factor.set_index(["date", "Code"], inplace=True)
total_factor.sort_index(level=["date", "Code"], inplace=True)

# 重建 DataFrame，使每个日期的股票数相同，缺失值用 NaN 补充
all_dates = total_factor.index.get_level_values("date").unique()
all_stocks = total_factor.index.get_level_values("Code").unique()
full_index = pd.MultiIndex.from_product([all_dates, all_stocks], names=["date", "Code"])
total_factor = total_factor.reindex(full_index)
total_factor.sort_index(level=["date", "Code"], inplace=True)
total_factor.columns = [str(i) for i in range(total_factor.shape[1] - 6)] + ['label', 'label_', 'qcut', 'weight', 'qid', 'amount']
total_factor.index = total_factor.index.set_levels(total_factor.index.levels[0].strftime("%Y%m%d").astype(int), level='date')
total_factor  # 6354516 rows × 2796 columns (index: 2020-01-02 - 2024-12-31)

                        0         1         2         3         4         5  \
date     Code
20210105 000001  0.071664  0.685760 -0.199404 -3.417535  0.258343 -5.388288
         000002  0.033293  0.756402 -0.061616 -0.923554  0.642608 -3.592522
         000004  0.041933  0.832400 -0.071108 -1.812693  0.475614 -1.823890
         000005  0.004317  0.958121 -0.026501 -1.706366  0.342068 -3.706094
         000006  0.000206  0.971685 -0.013775 -2.612419  0.450552 -1.542106
...                   ...       ...       ...       ...       ...       ...
20250214 688799  0.013516  0.000000  0.000000 -1.230162  0.000000 -1.700521
         688800  0.381315  0.542528 -0.096741  0.441431  0.576844  1.263855
         688819  0.041408  0.942160 -0.039829 -2.833302  0.272820 -2.098373
         688981  0.126986  0.732891 -0.078574 -2.118357  0.554371  6.505091
         689009  0.144818  0.704181 -0.050320 -0.095442  0.695665  1.524697

                        6         7         8         9  ...      3045  \
date     Code                                            ...
20210105 000001  0.653179 -3.462629  0.279649  0.273523  ...  1.800029
         000002  0.808333 -0.903918  0.681142  0.681142  ...  1.959329
         000004  0.606061 -1.799145  0.530543  0.530543  ...  0.716246
         000005  0.241379 -1.712731  0.357973  0.357973  ...  0.191443
         000006  0.620690 -2.554165  0.506740  0.502861  ...  0.496166
...                   ...       ...       ...       ...  ...       ...
20250214 688799  0.000000 -1.153934  0.000000  0.000000  ...  0.000000
         688800  1.405405  0.448139  0.671871  0.661052  ...  0.000000
         688819  0.617021 -2.736076  0.305844  0.306088  ...  0.000000
         688981  1.456559 -2.026053  0.633592  0.618463  ...  0.000000
         689009  1.312500 -0.082578  0.778158  0.762525  ...  0.000000

                     3046      3047      3048     label    label_  qcut  \
date     Code
20210105 000001  0.173608  1.884261  0.436159  0.056047  0.056047   0.0
         000002  0.148608  1.831184  0.349514  0.027921  0.027921   0.0
         000004  1.154439  0.633216  1.046688 -0.054570 -0.054570   0.0
         000005  1.687688  0.614557  1.668922 -0.054615 -0.054615   0.0
         000006  1.596688  0.538494  1.605645 -0.028815 -0.028815   0.0
...                   ...       ...       ...       ...       ...   ...
20250214 688799  0.000000  0.000000  0.000000 -0.006603 -0.004346   0.0
         688800  0.000000  0.000000  0.000000 -0.007086 -0.005070   0.0
         688819  0.000000  0.000000  0.000000 -0.005179 -0.002209   0.0
         688981  0.000000  0.000000  0.000000 -0.002473  0.001849   0.0
         689009  0.000000  0.000000  0.000000  0.055198  0.055198   0.0

                 weight  qid        amount
date     Code
20210105 000001     0.0  0.0  5.037920e+06
         000002     0.0  0.0  1.114534e+07
         000004     0.0  0.0  1.849760e+05
         000005     0.0  0.0  3.843000e+04
         000006     0.0  0.0  3.630000e+04
...                 ...  ...           ...
20250214 688799     0.0  0.0  0.000000e+00
         688800     0.0  0.0  1.025376e+06
         688819     0.0  0.0  5.956757e+04
         688981     0.0  0.0  2.000000e+07
         689009     0.0  0.0  1.196299e+06

[5181722 rows x 3055 columns]

# 保存数据

In [12]:
grouped = total_factor[[str(i) for i in range(total_factor.shape[1] - 6)]]
grouped.to_pickle('/home/datamake117/data/haris/dataset_0326/grouped_adj.pkl')  # 仅因子
grouped  # 6354516 rows × 2790 columns (index: 2020-01-02 - 2024-12-31)

                        0         1         2         3         4         5  \
date     Code
20210105 000001  0.071664  0.685760 -0.199404 -3.417535  0.258343 -5.388288
         000002  0.033293  0.756402 -0.061616 -0.923554  0.642608 -3.592522
         000004  0.041933  0.832400 -0.071108 -1.812693  0.475614 -1.823890
         000005  0.004317  0.958121 -0.026501 -1.706366  0.342068 -3.706094
         000006  0.000206  0.971685 -0.013775 -2.612419  0.450552 -1.542106
...                   ...       ...       ...       ...       ...       ...
20250214 688799  0.013516  0.000000  0.000000 -1.230162  0.000000 -1.700521
         688800  0.381315  0.542528 -0.096741  0.441431  0.576844  1.263855
         688819  0.041408  0.942160 -0.039829 -2.833302  0.272820 -2.098373
         688981  0.126986  0.732891 -0.078574 -2.118357  0.554371  6.505091
         689009  0.144818  0.704181 -0.050320 -0.095442  0.695665  1.524697

                        6         7         8         9  ...      3039  \
date     Code                                            ...
20210105 000001  0.653179 -3.462629  0.279649  0.273523  ...  0.936759
         000002  0.808333 -0.903918  0.681142  0.681142  ...  0.936739
         000004  0.606061 -1.799145  0.530543  0.530543  ...  0.715285
         000005  0.241379 -1.712731  0.357973  0.357973  ...  0.015238
         000006  0.620690 -2.554165  0.506740  0.502861  ...  0.245058
...                   ...       ...       ...       ...  ...       ...
20250214 688799  0.000000 -1.153934  0.000000  0.000000  ...  0.000000
         688800  1.405405  0.448139  0.671871  0.661052  ...  0.000000
         688819  0.617021 -2.736076  0.305844  0.306088  ...  0.000000
         688981  1.456559 -2.026053  0.633592  0.618463  ...  0.000000
         689009  1.312500 -0.082578  0.778158  0.762525  ...  0.000000

                     3040      3041      3042      3043      3044      3045  \
date     Code
20210105 000001  1.827603  1.958937  1.849779  1.808007  1.899696  1.800029
         000002  1.901046  1.963761  1.948429  1.807443  1.835787  1.959329
         000004  0.681892  0.970457  0.567955  0.593723  0.456899  0.716246
         000005  0.226351  0.646961  0.835797  0.000000  0.508222  0.191443
         000006  0.279683  0.761822  0.763092  0.375067  0.543365  0.496166
...                   ...       ...       ...       ...       ...       ...
20250214 688799  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         688800  0.000000  0.000000  0.000000  1.692345  0.000000  0.000000
         688819  0.000000  0.000000  0.000000  1.178699  0.000000  0.000000
         688981  0.000000  0.000000  0.000000  1.996996  0.000000  0.000000
         689009  0.000000  0.000000  0.000000  1.876587  0.000000  0.000000

                     3046      3047      3048
date     Code
20210105 000001  0.173608  1.884261  0.436159
         000002  0.148608  1.831184  0.349514
         000004  1.154439  0.633216  1.046688
         000005  1.687688  0.614557  1.668922
         000006  1.596688  0.538494  1.605645
...                   ...       ...       ...
20250214 688799  0.000000  0.000000  0.000000
         688800  0.000000  0.000000  0.000000
         688819  0.000000  0.000000  0.000000
         688981  0.000000  0.000000  0.000000
         689009  0.000000  0.000000  0.000000

[5181722 rows x 3049 columns]

In [13]:
grouped_label = total_factor[['label', 'qcut', 'weight', 'qid', 'amount']]
grouped_label.to_pickle('/home/datamake117/data/haris/dataset_0326/grouped_label_adj.pkl')  # 仅标签
grouped_label  # 6354516 rows × 5 columns (index: 2020-01-02 - 2024-12-31)

                    label  qcut  weight  qid        amount
date     Code
20210105 000001  0.056047   0.0     0.0  0.0  5.037920e+06
         000002  0.027921   0.0     0.0  0.0  1.114534e+07
         000004 -0.054570   0.0     0.0  0.0  1.849760e+05
         000005 -0.054615   0.0     0.0  0.0  3.843000e+04
         000006 -0.028815   0.0     0.0  0.0  3.630000e+04
...                   ...   ...     ...  ...           ...
20250214 688799 -0.006603   0.0     0.0  0.0  0.000000e+00
         688800 -0.007086   0.0     0.0  0.0  1.025376e+06
         688819 -0.005179   0.0     0.0  0.0  5.956757e+04
         688981 -0.002473   0.0     0.0  0.0  2.000000e+07
         689009  0.055198   0.0     0.0  0.0  1.196299e+06

[5181722 rows x 5 columns]

In [15]:
daily_amount = pd.read_feather(r"/home/datamake117/test0326/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')

daily_amount_shift = daily_amount
intersection = [col for col in list(grouped_label.loc[20210701].index) if col in daily_amount_shift.columns]
daily_amount_shift = daily_amount_shift[intersection]
daily_amount_shift = daily_amount_shift.fillna(0)
daily_amount_shift.to_pickle('/home/datamake117/data/haris/dataset_0326/grouped_liquidity.pkl')  # 流动性指标
daily_amount_shift  # 1487 rows × 5243 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688787,688788,688789,688793,688798,688799,688800,688819,688981,689009
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,1828702.50,1.552751e+06,0.0,6725.0,8547.0,141277.5,158712.0,231637.50,21125.0,18860.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
2019-01-03,1384206.30,2.545530e+05,803.0,6164.0,5665.0,129523.5,17802.0,37450.00,37341.5,931.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
2019-01-04,1747746.00,7.256685e+05,4890.0,5206.5,33848.5,234090.0,163020.0,63840.00,26732.0,86118.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
2019-01-07,12167652.00,1.058007e+07,44847.0,65469.0,619530.0,258303.5,473605.0,223050.50,17149.5,200098.5,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
2019-01-08,1490636.00,1.761842e+06,14535.0,27406.0,184652.0,392445.0,621285.5,12711.00,9010.0,62144.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-18,15712704.00,2.125278e+06,247978.5,0.0,397377.0,98854.0,125227.5,622790.00,972664.0,92016.0,...,852676.285,899100.000,54825.700,56719.600,328738.500,20375.000,1644941.16,105632.660,5483611.575,680532.360
2025-03-19,7570026.80,1.873624e+06,79365.0,0.0,558315.0,49036.5,95821.0,829872.00,77265.0,58305.0,...,96695.790,61115.000,10545.965,125208.325,163676.625,43570.975,3347364.24,503494.000,5326618.350,3716009.375
2025-03-20,4552780.50,1.036571e+06,45562.0,0.0,279500.0,28530.0,241026.0,151940.00,576216.0,46842.0,...,367289.820,243795.475,164249.160,559714.540,41742.750,4038.000,478980.15,177752.400,2682351.700,570374.865
2025-03-21,4157656.50,1.512190e+06,92015.0,0.0,614685.0,107702.0,299124.5,153786.00,68222.0,126925.5,...,3377676.750,594601.440,107980.600,2562141.120,305759.580,1039971.680,726497.50,237972.735,8292932.690,594314.050
2025-03-24,2769264.05,8.831025e+05,1381789.5,0.0,2032101.0,139285.0,243432.0,82015.01,281214.0,373912.5,...,2516430.000,125225.850,137166.630,1030473.600,235566.545,115089.360,51880.00,154417.205,4850872.500,153427.885

In [16]:
temp = grouped_label.reset_index()[['date', 'Code']]
temp.to_pickle('/home/datamake117/data/haris/dataset_0326/total_date.pkl')  # 日期+股票代码
temp  # 6354516 rows × 2 columns

             date    Code
0        20210105  000001
1        20210105  000002
2        20210105  000004
3        20210105  000005
4        20210105  000006
...           ...     ...
5181717  20250214  688799
5181718  20250214  688800
5181719  20250214  688819
5181720  20250214  688981
5181721  20250214  689009

[5181722 rows x 2 columns]

In [ ]:
temp.Code.unique().shape

(5213,)

: