In [1]:
import os
import pandas as pd
from tqdm.notebook import tqdm
from datetime import datetime

# 读取标签

In [2]:
label = pd.read_feather("/home/datamake117/test0121/label_divide1_5.fea")
label['index'] = pd.to_datetime(label['index'])
label = label.set_index('index', drop=True)
label  # 1494 rows × 5314 columns (index: 2019-01-02 - 2025-03-04)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,301275,603271,301479,301501,603124,001382,301629,688757,301535,301616
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-02,0.016034,0.015087,-0.012903,NaN,-0.027927,0.019454,0.101420,0.006813,0.011593,0.015118,...,0.010729,0.018213,0.011555,0.061736,0.033681,0.101986,-0.031373,0.033440,NaN,NaN
2025-04-03,0.049819,0.046611,-0.004218,NaN,-0.006884,0.015519,0.103754,0.007931,0.007668,0.020222,...,-0.013093,0.034465,-0.024411,0.013265,0.029833,0.094022,0.120874,0.011270,0.010496,-0.043115
2025-04-07,0.072352,0.079970,0.017901,NaN,-0.030111,-0.028060,0.122551,0.047848,-0.022395,-0.004279,...,0.018157,-0.026658,0.029844,0.027724,-0.022420,-0.039408,0.059435,0.051997,-0.030431,-0.015790
2025-04-08,-0.017653,0.040808,0.017047,NaN,-0.042223,-0.017860,0.095624,-0.001899,0.004584,0.000058,...,-0.050318,-0.078818,-0.030163,-0.030787,-0.083115,-0.160611,-0.096113,0.020457,-0.029448,-0.074264
2025-04-09,-0.024921,0.033862,0.020935,NaN,0.048521,0.047086,0.101026,-0.000388,0.052852,0.031816,...,0.007895,-0.009940,-0.002745,-0.009786,-0.004072,-0.019583,-0.012350,-0.001519,-0.027540,-0.014703

In [3]:
label_ = pd.read_feather("/home/datamake117/test0121/label.fea")  # 使用不调整的label构造相关性矩阵
label_['index'] = pd.to_datetime(label_['index'])
label_ = label_.set_index('index', drop=True)
label_  # 1487 rows × 5313 columns (index: 2019-01-02 - 2025-02-21)

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,301479,301501,603124,001382,301629,688757,301535,301616,301658,603257
index,,,,,,,,,,,,,,,,,,,,,
2019-01-02,0.001536,0.023322,0.025712,0.009533,0.007459,-0.014079,0.000397,-0.012037,0.022481,0.034990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,0.042991,0.028819,0.014524,0.007019,0.002259,-0.027774,-0.008764,0.001928,-0.009982,0.007752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,0.011437,0.005003,0.013766,0.020995,0.006440,0.010919,0.028377,0.016848,0.000269,0.016720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,-0.034066,-0.027240,-0.003732,0.002213,-0.021380,-0.047832,0.032328,0.004543,-0.003761,-0.010613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-08,0.021478,0.011073,-0.018818,0.006938,-0.000105,0.001130,0.004809,0.004380,-0.003046,0.001955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-09,-0.024921,0.033862,0.020935,NaN,0.048521,0.047086,0.101026,-0.000388,0.052852,0.031816,...,0.018899,0.008337,-0.004072,-0.019583,0.004492,0.020738,-0.018293,0.000963,NaN,NaN
2025-04-10,-0.023258,-0.014592,0.000915,NaN,0.022313,0.031122,0.030919,-0.022150,-0.006179,-0.024752,...,-0.006589,-0.019918,-0.007049,-0.043213,0.007878,0.071110,-0.036478,-0.074618,-0.087367,NaN
2025-04-11,-0.009464,-0.026204,-0.000854,NaN,0.039924,0.059154,0.015116,0.024180,-0.007172,0.000225,...,0.035699,0.020336,0.089652,0.043167,0.055883,0.111713,0.063756,0.058567,0.007598,NaN
2025-04-14,-0.003801,-0.013716,0.111416,NaN,0.004225,0.004560,-0.030557,-0.003801,0.027087,-0.001276,...,-0.032391,0.038393,0.020496,0.121079,-0.020958,-0.009357,0.068325,0.033359,-0.024709,NaN
2025-04-15,0.019814,0.012488,0.054200,NaN,-0.012788,-0.024549,-0.056819,-0.005034,-0.006892,-0.001296,...,-0.000369,0.062212,0.018647,0.062960,-0.035958,-0.026035,0.042201,-0.020921,-0.025667,0.017288

# 读取特征
## 读取特征0（1250个）

In [5]:
year = 2020
os.chdir(r"/home/datamake117/test0121/feature0")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor1 = pd.concat(factor_list)
factor1  # 5398930 rows × 1252 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/1279 [00:00<?, ?it/s]

,date,Code,0,1,2,3,4,5,6,7,...,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249
0,2020-01-02,000001,0.161906,0.715487,0.093825,2.500486,1.495386,3.687422,1.265125,2.488541,...,0.014142,0.074876,0.033301,0.050662,0.063640,0.035355,0.028284,0.014142,0.014142,0.014142
1,2020-01-02,000002,0.233131,0.554393,-0.052147,0.148151,0.797523,-4.361952,0.735354,0.153694,...,-0.007071,-0.099301,-0.065184,-0.065184,-0.079073,-0.028251,-0.030000,-0.030000,-0.007071,-0.007071
2,2020-01-02,000004,0.129032,0.902306,-0.089413,-3.294483,0.073779,-4.185775,0.243243,-3.187878,...,0.000000,-0.412997,-0.412997,-0.412997,-0.304138,-0.275379,-0.229420,-0.149332,-0.028284,0.000000
3,2020-01-02,000005,0.003936,0.962999,0.011201,-2.758275,1.244934,-4.228945,0.402985,-2.640067,...,0.000000,-0.012910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2020-01-02,000006,0.059158,0.808410,-0.066815,0.230044,0.572983,-3.184859,0.476190,0.285741,...,0.000000,-0.049497,-0.014142,-0.014142,-0.014142,-0.014142,-0.014142,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954,2025-04-15,688799,0.000000,0.958354,-0.028160,-3.401972,0.286125,-5.698514,0.076923,-3.398105,...,-0.028284,-0.551483,-0.551483,-0.551483,-0.339411,-0.339411,-0.339411,-0.268701,-0.190919,-0.176777
4955,2025-04-15,688800,0.546698,0.438042,-0.324099,-0.570970,0.217954,-3.344614,0.405405,-0.526954,...,0.014142,0.295873,0.208515,0.208515,0.062278,0.040825,0.040825,0.037639,0.041130,0.038297
4956,2025-04-15,688819,0.114161,0.888225,-0.081789,-3.859348,0.217411,-4.930976,0.271186,-3.765319,...,-0.020817,-0.269490,-0.269490,-0.269490,-0.269490,-0.187705,-0.187705,-0.020817,-0.020817,-0.020817
4957,2025-04-15,688981,0.120903,0.889714,-0.061842,-2.020387,0.340601,-1.404904,0.894144,-1.812097,...,0.115974,0.532696,0.225222,0.225222,0.222530,0.222530,0.141093,0.164560,0.164560,0.164560
4958,2025-04-15,689009,0.273325,0.938030,0.030161,2.851556,1.269770,6.156049,3.444444,2.886939,...,0.164595,0.771531,0.304375,0.241339,0.262805,0.288238,0.311812,0.311595,0.301704,0.291819

## 读取特征1（1540个）

In [6]:
year = 2020
os.chdir(r"/home/datamake117/test0121/feature1")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor2 = pd.concat(factor_list)
factor2.columns = ['date', 'Code'] + [str(i) for i in range((len(factor1.columns) - 2), ((len(factor1.columns) - 2) + (len(factor2.columns) - 2)))]
factor2  # 5398930 rows × 1542 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/1279 [00:00<?, ?it/s]

,date,Code,1250,1251,1252,1253,1254,1255,1256,1257,...,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789
0,2020-01-02,000001,-0.000371,0.144566,0.167514,0.030235,-0.043070,0.358179,1.350860,0.139044,...,0.0,0.0,0.0,0.0,-1.0,10500.0,70.0,1.0,0.100181,0.0
1,2020-01-02,000002,0.000338,0.150542,0.113075,0.056990,0.026726,0.505274,1.306157,0.319926,...,0.0,0.0,0.0,0.0,-1.0,10564.0,67.0,1.0,0.100095,0.0
2,2020-01-02,000004,-0.000049,0.131501,0.216560,-0.000914,-0.087498,0.387429,2.045524,0.131223,...,0.0,0.0,0.0,0.0,-1.0,10579.0,61.0,0.0,0.100044,0.0
3,2020-01-02,000005,0.000024,0.168856,0.170853,0.016271,0.002746,0.417996,1.513899,0.215653,...,0.0,0.0,0.0,0.0,-1.0,10605.0,62.0,0.0,0.100649,0.0
4,2020-01-02,000006,-0.000474,0.141803,0.150814,-0.003795,0.018822,0.384158,1.462300,0.175712,...,0.0,0.0,0.0,0.0,-1.0,10110.0,62.0,1.0,0.099624,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954,2025-04-15,688799,0.000075,0.170455,0.154334,0.024986,0.007773,0.417390,4.055467,0.322065,...,0.0,0.0,0.0,0.0,2.0,1372.0,167.0,1.0,0.200000,0.0
4955,2025-04-15,688800,-0.000485,0.156364,0.185447,0.015918,-0.037410,0.382323,1.838807,0.207873,...,0.0,0.0,0.0,0.0,2.0,1363.0,171.0,1.0,0.200046,0.0
4956,2025-04-15,688819,0.000086,0.194875,0.165020,0.001939,0.007131,0.382076,1.637791,0.173212,...,0.0,0.0,0.0,0.0,2.0,1548.0,17.0,1.0,0.200080,0.0
4957,2025-04-15,688981,-0.000563,0.178102,0.176722,0.108055,-0.018009,0.359097,1.315726,0.184259,...,0.0,0.0,0.0,0.0,2.0,1734.0,17.0,1.0,0.200000,0.0
4958,2025-04-15,689009,-0.000388,0.150694,0.152313,0.025801,0.010693,0.448910,2.201621,0.222145,...,0.0,0.0,0.0,0.0,2.0,1629.0,2.0,1.0,0.200000,0.0

# 读取特征2（494个）

In [7]:
year = 2020
os.chdir(r"/home/datamake117/test_zjh")
date_list = sorted(filter(lambda x: x[0] == "2" and int(x[:4]) >= year, os.listdir()))

factor_list = []
for file in tqdm(date_list):  # 将所有日期的因子数据合并
    dt = datetime.strptime(file[:-4], "%Y%m%d").date()
    factor = pd.read_feather(file)
    factor.fillna(0.0, inplace=True)
    factor.insert(loc=0, column="date", value=dt)
    factor_list.append(factor)

factor3 = pd.concat(factor_list)
factor3.columns = ['date', 'Code'] + [str(i) for i in range(
        (len(factor1.columns) - 2) + (len(factor2.columns) - 2), 
        (len(factor1.columns) - 2) + (len(factor2.columns) - 2) + (len(factor3.columns) - 2)
    )]
factor3  # 5398930 rows × 1542 columns (index: 2020-01-02 - 2024-12-31)

  0%|          | 0/994 [00:00<?, ?it/s]

,date,Code,2790,2791,2792,2793,2794,2795,2796,2797,...,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048
0,2021-01-05,000001,1.955638,1.433724,0.158018,0.978352,1.885833,1.711484,1.906433,1.776793,...,0.936759,1.827603,1.958937,1.849779,1.808007,1.899696,1.800029,0.173608,1.884261,0.436159
1,2021-01-05,000002,1.968860,1.890906,0.041938,0.995510,1.944617,1.893008,1.938672,1.767126,...,0.936739,1.901046,1.963761,1.948429,1.807443,1.835787,1.959329,0.148608,1.831184,0.349514
2,2021-01-05,000004,0.672563,1.225363,1.017202,0.014161,0.917882,0.904124,0.815707,0.536514,...,0.715285,0.681892,0.970457,0.567955,0.593723,0.456899,0.716246,1.154439,0.633216,1.046688
3,2021-01-05,000005,0.745879,0.082460,1.274166,0.142016,0.145241,0.044671,0.129795,0.240523,...,0.015238,0.226351,0.646961,0.835797,0.000000,0.508222,0.191443,1.687688,0.614557,1.668922
4,2021-01-05,000006,1.326767,0.179102,1.701469,0.570617,0.492514,0.362141,0.158265,0.142948,...,0.245058,0.279683,0.761822,0.763092,0.375067,0.543365,0.496166,1.596688,0.538494,1.605645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5603,2025-02-14,603194,0.000000,0.000000,1.084162,0.000000,1.781506,0.000000,1.616845,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.377317,0.000000,0.000000,0.000000,0.000000,0.000000
5604,2025-02-14,688411,0.000000,0.000000,0.079063,0.000000,1.697410,0.000000,1.707913,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.410057,0.000000,0.000000,0.000000,0.000000,0.000000
5605,2025-02-14,688545,0.000000,0.000000,0.894139,0.000000,1.711764,0.000000,1.668883,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.356526,0.000000,0.000000,0.000000,0.000000,0.000000
5606,2025-02-14,688583,0.000000,0.000000,0.191052,0.000000,1.386516,0.000000,1.871014,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.541997,0.000000,0.000000,0.000000,0.000000,0.000000
5607,2025-02-14,688758,0.000000,0.000000,0.985937,0.000000,0.610378,0.000000,0.985369,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## 合并全部特征（3284个）

In [ ]:
total_factor = pd.merge(factor1, factor2, how='inner', on=['date', 'Code'])
total_factor = pd.merge(total_factor, factor3, how='inner', on=['date', 'Code'])
total_factor  # 5398930 rows × 2792 columns (index: 2020-01-02 - 2024-12-31)

# 合并特征和标签

In [ ]:
def look(date, Code):
    try:
        return label.loc[str(date), Code]
    except:
        return None
    
def look_(date, Code):
    try:
        return label_.loc[str(date), Code]
    except:
        return None

total_factor['label'] = [look(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['label_'] = [look_(str(date), Code) for date, Code in zip(total_factor['date'], total_factor['Code'])]
total_factor['date'] = total_factor['date'].astype("datetime64[ns]")
total_factor  # 5398930 rows × 2794 columns (index: 2020-01-02 - 2024-12-31)

# 增加可成交量变量

In [ ]:
total_factor['qcut'] = 0
total_factor['weight'] = 0
total_factor['qid'] = 0

daily_amount = pd.read_feather(r"/home/datamake117/test0121/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')
lookup_dict = daily_amount.stack().to_dict()
total_factor['amount'] = total_factor.set_index(['date', 'Code']).index.map(lookup_dict)
total_factor.to_pickle('/home/datamake117/data/haris/dataset_0121_zjh/total_factor.pkl')  # 因子+标签
total_factor  # 5398930 rows × 2798 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
# 设置两级索引，第一级为日期，第二级为股票代码
total_factor.set_index(["date", "Code"], inplace=True)
total_factor.sort_index(level=["date", "Code"], inplace=True)

# 重建 DataFrame，使每个日期的股票数相同，缺失值用 NaN 补充
all_dates = total_factor.index.get_level_values("date").unique()
all_stocks = total_factor.index.get_level_values("Code").unique()
full_index = pd.MultiIndex.from_product([all_dates, all_stocks], names=["date", "Code"])
total_factor = total_factor.reindex(full_index)
total_factor.sort_index(level=["date", "Code"], inplace=True)
total_factor.columns = [str(i) for i in range(3284)] + ['label', 'label_', 'qcut', 'weight', 'qid', 'amount']
total_factor.index = total_factor.index.set_levels(total_factor.index.levels[0].strftime("%Y%m%d").astype(int), level='date')
total_factor  # 6354516 rows × 2796 columns (index: 2020-01-02 - 2024-12-31)

# 保存数据

In [ ]:
grouped = total_factor[[str(i) for i in range(3284)]]
grouped.to_pickle('/home/datamake117/data/haris/dataset_0121_zjh/grouped_adj.pkl')  # 仅因子
grouped  # 6354516 rows × 3284 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
grouped_label = total_factor[['label', 'qcut', 'weight', 'qid', 'amount']]
grouped_label.to_pickle('/home/datamake117/data/haris/dataset_0121_zjh/grouped_label_adj.pkl')  # 仅标签
grouped_label  # 6354516 rows × 5 columns (index: 2020-01-02 - 2024-12-31)

In [ ]:
daily_amount = pd.read_feather(r"/home/datamake117/test0121/can_trade_amt_1000.fea")
daily_amount['index'] = pd.to_datetime(daily_amount['index'], format='%Y%m%d')
daily_amount = daily_amount.set_index(['index'], drop=True)
daily_amount.index = daily_amount.index.astype('datetime64[ns]')
daily_amount.columns = daily_amount.columns.astype('str')

daily_amount_shift = daily_amount
intersection = [col for col in list(grouped_label.loc[20200701].index) if col in daily_amount_shift.columns]
daily_amount_shift = daily_amount_shift[intersection]
daily_amount_shift = daily_amount_shift.fillna(0)
daily_amount_shift.to_pickle('/home/datamake117/data/haris/dataset_0121_zjh/grouped_liquidity.pkl')  # 流动性指标
daily_amount_shift  # 1487 rows × 5243 columns (index: 2019-01-02 - 2025-02-21)

In [ ]:
temp = grouped_label.reset_index()[['date', 'Code']]
temp.to_pickle('/home/datamake117/data/haris/dataset_0121_zjh/total_date.pkl')  # 日期+股票代码
temp  # 6354516 rows × 2 columns